version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  cypress: cypress-io/cypress@1.29.0
  allure: ayte/allure@0.1.3

jobs:
  allure-install:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - allure/install
  allure-report:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - allure/report
      - run: npm run clean

workflows:
  api_tests:
    when:
        and:
          - << pipeline.parameters.GHA_Event >>
          - equal: [ "api_tests", << pipeline.parameters.GHA_Action >>]    
    jobs:
      - allure-install
      - cypress/run:
          pre-steps:
            - run: echo << pipeline.git.branch >>
          store_artifacts: true
          post-install:
          - run: npm run test:api || true
          requires:
            - allure-install
      - allure-report:
          filters:
              branches:
                only:
                  - << pipeline.git.branch >>
          requires:
            - cypress/run