version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0
  allure: ayte/allure@0.1.3

workflows:
  build:
    jobs:
      - cypress/run:
          post-install:
          - run: npm run clean
          - run: npm run test || true
          post-steps:
          - run: npm run post
          - store_artifacts:
              path: allure-report
        
