version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0
  allure: ayte/allure@0.1.3

workflows:
  tests:
    jobs:  
      - cypress/run:
          name: api_tests
          store_artifacts: true
          command: npm run test:api || true
      - cypress/run:
          name: smoke_tests
          store_artifacts: true
          command: npm run test:smoke || true
