version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  cypress: cypress-io/cypress@1.29.0
  allure: ayte/allure@0.1.3

jobs:
  report:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - allure/install
      - allure/report

workflows:
  conditional-workflow:
    when: << pipeline.parameters.GHA_Action >>

    jobs:
      - cypress/run:
          store_artifacts: true
          post-install:
          - run: npm run clean
          - run: npm run test:api || true
      - report:
          requires:
            - cypress/run
