version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0
  
workflows:
  build:
    jobs:
      - cypress/run:
          post-install:
          - run: npm run clean
          - run: npm run test || true
      - generate allure report:
          name: Generation of Allure Report
          command: npm run post
          when: always
      - store_test_results:
          path: /home/circleci/project/allure-results
      - store_artifacts:
          path: /home/circleci/project/allure-report
