version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0
  allure: ayte/allure@0.1.3

jobs:
  report:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - allure/install
      - allure/report

workflows:
  tests:
    jobs:  
      - cypress/run:
          name: api_tests
          store_artifacts: true
          command: npm run test:api || true
      - cypress/run:
          name: smoke
          store_artifacts: true
          command: npm run test:smoke || true
