version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0
  allure: ayte/allure@0.1.3

jobs:
  report:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - allure/install
      - allure/report

workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
          post-install:
          - run: npm run clean
          - run: npm run test || true
      - report:
          requires:
            - cypress/run
